name: DevSecOps CD Pipeline - Deploy

# Cand se declanseaza? Doar dupa ce CI-ul s-a terminat cu SUCCES
on:
  workflow_run:
    workflows: ["DevSecOps CI Pipeline"]
    types:
      - completed

jobs:
  deploy-to-server:
    # Ruleaza doar daca robotul de CI a dat "verde"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Pasul 1: Luam codul curent
      - name: Checkout Code
        uses: actions/checkout@v4

      # Pasul 2: Copiem fisierele pe serverul tau prin SSH
      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/home/bbm/devsecops_portfolio"
          rm: false # Safeguard the server-side .env file

      # Pasul 3: Intram pe server si pornim Docker-ul
      - name: Deploy cu Docker pe Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/bbm/devsecops_portfolio
            # Oprim versiunea veche daca exista
            docker stop portfolio-app || true
            docker rm portfolio-app || true
            # Construim imaginea noua din codul adus proaspat
            docker build -t bbm-portfolio .
            # Pornim aplicatia cu env-file si restart policy
            docker run -d \
              --name portfolio-app \
              --restart unless-stopped \
              -p 5000:5000 \
              -v /var/log/auth.log:/app/host_auth.log:ro \
              --env-file /home/bbm/devsecops_portfolio/.env \
              bbm-portfolio
